
DEFAULT_PORT = 8080
CLIENT_TIMEOUT = 30
CLIENT_LOGOUT_AFTER = 60
MESSAGES_PER_SECOND = 10000
CHANNELS_URI_PATH = "/channels"
HANDSHAKE_URI_PATH = "/handshake"
CHANNELS_SEP = "|"
DEFAULT_FORMAT = "json"
JSONP_REQUIRED_SUBSTR = "_JSONP_"
DEFAULT_JSONP_CB = JSONP_REQUIRED_SUBSTR + "comet_cb"
QUOTE_JSONP = False
HTTP_CACHE_AGE = 86400 * 90
DEFAULT_MAX_MESSAGES_PER_CHANNEL = 5
